Update setup.py to resolve breaking dependency
The package gave the following error
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

Edit setup.py to unpin jinja2 version to resolve this.
Add nltk which is a required dependency